name: Ping server
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  check-server:
    runs-on: ubuntu-20.04
    steps:
      - name: ping server
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://polar-headland-92577.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
