name: Hello world
on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo Hello World!

      - name: Now it is
        run: date

      - name: Directory content
        run: ls -l
