name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.base_ref	== 'refs/heads/master' }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "polar-headland-92577"
          heroku_email: "mggurpude@mitaoe.ac.in"
          healthcheck: "https://polar-headland-92577.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: Send success to discord
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
      - name: Send error to discord
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Bump version and push tag
        if: ${{ github.base_ref == 'refs/heads/master' }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
